In [ ]:
# 박소연 2024109435

In [2]:
import pandas as pd

In [3]:
csv_path = 'C:/Users/SY Park/Downloads/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)

In [4]:
q = df[['Rating']]
q

   Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5

In [5]:
q = df[['Released', 'Artist']]
q

   Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

In [7]:
#df.iloc[1, 2]
df.iloc[1, 2].item()

1980